

const envVars = process.env;


const API_KEY = envVars.API_KEY!;
const APPWRITE_PROJECT_ID = envVars.APPWRITE_PROJECT_ID!;
const APPWRITE_PROJECT_NAME = envVars.APPWRITE_PROJECT_NAME!;
const APPWRITE_ENDPOINT = envVars.APPWRITE_ENDPOINT!;
const APPWRITE_DATABASE_ID = envVars.APPWRITE_DATABASE_ID!;
const APPWRITE_COLLECTION_ID = envVars.APPWRITE_COLLECTION_ID!;

export { API_KEY, APPWRITE_PROJECT_ID, APPWRITE_PROJECT_NAME, APPWRITE_ENDPOINT, APPWRITE_DATABASE_ID, APPWRITE_COLLECTION_ID };